/**
 * This class is generated by jOOQ
 */
package org.baddev.currency.jooq.schema.tables.records;


import org.baddev.currency.jooq.schema.tables.ExchangeOperationNotification;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeOperationNotificationRecord extends TableRecordImpl<ExchangeOperationNotificationRecord> implements Record2<Long, Byte> {

	private static final long serialVersionUID = 1536425250;

	/**
	 * Setter for <code>exchanger.exchange_operation_notification.exchange_opration_id</code>.
	 */
	public void setExchangeOprationId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>exchanger.exchange_operation_notification.exchange_opration_id</code>.
	 */
	public Long getExchangeOprationId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>exchanger.exchange_operation_notification.ui_notification</code>.
	 */
	public void setUiNotification(Byte value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>exchanger.exchange_operation_notification.ui_notification</code>.
	 */
	public Byte getUiNotification() {
		return (Byte) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Byte> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Long, Byte> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return ExchangeOperationNotification.EXCHANGE_OPERATION_NOTIFICATION.EXCHANGE_OPRATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field2() {
		return ExchangeOperationNotification.EXCHANGE_OPERATION_NOTIFICATION.UI_NOTIFICATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getExchangeOprationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value2() {
		return getUiNotification();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExchangeOperationNotificationRecord value1(Long value) {
		setExchangeOprationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExchangeOperationNotificationRecord value2(Byte value) {
		setUiNotification(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExchangeOperationNotificationRecord values(Long value1, Byte value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExchangeOperationNotificationRecord
	 */
	public ExchangeOperationNotificationRecord() {
		super(ExchangeOperationNotification.EXCHANGE_OPERATION_NOTIFICATION);
	}

	/**
	 * Create a detached, initialised ExchangeOperationNotificationRecord
	 */
	public ExchangeOperationNotificationRecord(Long exchangeOprationId, Byte uiNotification) {
		super(ExchangeOperationNotification.EXCHANGE_OPERATION_NOTIFICATION);

		setValue(0, exchangeOprationId);
		setValue(1, uiNotification);
	}
}
