/**
 * This class is generated by jOOQ
 */
package org.baddev.currency.jooq.schema.tables.records;


import org.baddev.currency.jooq.schema.tables.ExchangeOperation;
import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExchangeOperationRecord extends UpdatableRecordImpl<ExchangeOperationRecord> implements Record7<Long, String, String, Double, Double, LocalDate, LocalDateTime> {

    private static final long serialVersionUID = -1575758786;

    /**
     * Setter for <code>exchanger.exchange_operation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>exchanger.exchange_operation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>exchanger.exchange_operation.from_ccy</code>.
     */
    public void setFromCcy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>exchanger.exchange_operation.from_ccy</code>.
     */
    public String getFromCcy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>exchanger.exchange_operation.to_ccy</code>.
     */
    public void setToCcy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>exchanger.exchange_operation.to_ccy</code>.
     */
    public String getToCcy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>exchanger.exchange_operation.from_amount</code>.
     */
    public void setFromAmount(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>exchanger.exchange_operation.from_amount</code>.
     */
    public Double getFromAmount() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>exchanger.exchange_operation.to_amount</code>.
     */
    public void setToAmount(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>exchanger.exchange_operation.to_amount</code>.
     */
    public Double getToAmount() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>exchanger.exchange_operation.rates_date</code>.
     */
    public void setRatesDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>exchanger.exchange_operation.rates_date</code>.
     */
    public LocalDate getRatesDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>exchanger.exchange_operation.perform_datetime</code>.
     */
    public void setPerformDatetime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>exchanger.exchange_operation.perform_datetime</code>.
     */
    public LocalDateTime getPerformDatetime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Double, Double, LocalDate, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Double, Double, LocalDate, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ExchangeOperation.EXCHANGE_OPERATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ExchangeOperation.EXCHANGE_OPERATION.FROM_CCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ExchangeOperation.EXCHANGE_OPERATION.TO_CCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return ExchangeOperation.EXCHANGE_OPERATION.FROM_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return ExchangeOperation.EXCHANGE_OPERATION.TO_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field6() {
        return ExchangeOperation.EXCHANGE_OPERATION.RATES_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return ExchangeOperation.EXCHANGE_OPERATION.PERFORM_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFromCcy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getToCcy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getFromAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getToAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value6() {
        return getRatesDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getPerformDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeOperationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeOperationRecord value2(String value) {
        setFromCcy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeOperationRecord value3(String value) {
        setToCcy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeOperationRecord value4(Double value) {
        setFromAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeOperationRecord value5(Double value) {
        setToAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeOperationRecord value6(LocalDate value) {
        setRatesDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeOperationRecord value7(LocalDateTime value) {
        setPerformDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExchangeOperationRecord values(Long value1, String value2, String value3, Double value4, Double value5, LocalDate value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExchangeOperationRecord
     */
    public ExchangeOperationRecord() {
        super(ExchangeOperation.EXCHANGE_OPERATION);
    }

    /**
     * Create a detached, initialised ExchangeOperationRecord
     */
    public ExchangeOperationRecord(Long id, String fromCcy, String toCcy, Double fromAmount, Double toAmount, LocalDate ratesDate, LocalDateTime performDatetime) {
        super(ExchangeOperation.EXCHANGE_OPERATION);

        set(0, id);
        set(1, fromCcy);
        set(2, toCcy);
        set(3, fromAmount);
        set(4, toAmount);
        set(5, ratesDate);
        set(6, performDatetime);
    }
}
