/**
 * This class is generated by jOOQ
 */
package org.baddev.currency.exchange.dao.jooq.schema;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.baddev.currency.exchange.dao.jooq.schema.tables.ExchangeOperation;
import org.baddev.currency.exchange.dao.jooq.schema.tables.ExchangeRate;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exchanger extends SchemaImpl {

	private static final long serialVersionUID = -1435416672;

	/**
	 * The reference instance of <code>exchanger</code>
	 */
	public static final Exchanger EXCHANGER = new Exchanger();

	/**
	 * No further instances allowed
	 */
	private Exchanger() {
		super("exchanger");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			ExchangeOperation.EXCHANGE_OPERATION,
			ExchangeRate.EXCHANGE_RATE);
	}
}
