/**
 * This class is generated by jOOQ
 */
package org.baddev.currency.jooq.schema;


import org.baddev.currency.jooq.schema.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exchanger extends SchemaImpl {

    private static final long serialVersionUID = -149669988;

    /**
     * The reference instance of <code>exchanger</code>
     */
    public static final Exchanger EXCHANGER = new Exchanger();

    /**
     * The table <code>exchanger.exchange_operation</code>.
     */
    public final ExchangeOperation EXCHANGE_OPERATION = org.baddev.currency.jooq.schema.tables.ExchangeOperation.EXCHANGE_OPERATION;

    /**
     * The table <code>exchanger.exchange_rate</code>.
     */
    public final ExchangeRate EXCHANGE_RATE = org.baddev.currency.jooq.schema.tables.ExchangeRate.EXCHANGE_RATE;

    /**
     * The table <code>exchanger.exchange_task</code>.
     */
    public final ExchangeTask EXCHANGE_TASK = org.baddev.currency.jooq.schema.tables.ExchangeTask.EXCHANGE_TASK;

    /**
     * The table <code>exchanger.user</code>.
     */
    public final User USER = org.baddev.currency.jooq.schema.tables.User.USER;

    /**
     * The table <code>exchanger.user_details</code>.
     */
    public final UserDetails USER_DETAILS = org.baddev.currency.jooq.schema.tables.UserDetails.USER_DETAILS;

    /**
     * The table <code>exchanger.user_role</code>.
     */
    public final UserRole USER_ROLE = org.baddev.currency.jooq.schema.tables.UserRole.USER_ROLE;

    /**
     * The table <code>exchanger.user_user_role</code>.
     */
    public final UserUserRole USER_USER_ROLE = org.baddev.currency.jooq.schema.tables.UserUserRole.USER_USER_ROLE;

    /**
     * No further instances allowed
     */
    private Exchanger() {
        super("exchanger", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ExchangeOperation.EXCHANGE_OPERATION,
            ExchangeRate.EXCHANGE_RATE,
            ExchangeTask.EXCHANGE_TASK,
            User.USER,
            UserDetails.USER_DETAILS,
            UserRole.USER_ROLE,
            UserUserRole.USER_USER_ROLE);
    }
}
